# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the minecraft version (without the 1.)
loaderVersion = "[18,)" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="" #optional

# A URL to refer people to when problems occur with this mod
issueTrackerURL = "https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL = "https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks" #optional

# License
license = "GNU General Public License v3.0"

# A file name (in the root of the mod JAR) containing a logo for display
logoFile = "logo.png" #optional

# A text field displayed in the mod UI
credits = "Created by P3pp3rF1y and art done by Ridanisaurus." #optional

# A text field displayed in the mod UI
authors="P3pp3rF1y, Ridanisaurus" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="sophisticatedbackpacks" #mandatory

# The version number of the mod
version="${file.jarVersion}" #mandatory

# A display name for the mod
displayName="Sophisticated Backpacks" #mandatory

# The description text for the mod (multi line!) (#mandatory)
description='''
Fancy and functional backpacks.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.sophisticatedbackpacks]]
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[39.0.0,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.sophisticatedbackpacks]]
modId="sophisticatedcore" #mandatory
mandatory=true #mandatory
versionRange = "[1.18.2-0.6.0,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"